package com.azure.runtime.host.utils.templates;

/**
 * Represents the output of processing a template file within the Java Runtime for Azure framework. This record encapsulates the
 * result of template processing, including the filename of the generated file and its content. The content is
 * currently represented as a String, suitable for text-based templates. Future enhancements may include support
 * for binary content to accommodate a wider range of template types.
 * <p>
 * The {@code filename} attribute specifies the name of the file that has been generated as a result of template
 * processing. This allows for easy identification and subsequent manipulation or deployment of the file. The
 * {@code content} attribute contains the actual text that was produced by the template engine, ready for use
 * within the application or for further processing.
 *
 * @param filename The name of the file generated by the template processing.
 * @param content  The text content of the generated file.
 */
// FIXME at some point string content won't be sufficient, and we will want to support binary content too
public record TemplateFileOutput(String filename, String content) {    }