package com.azure.runtime.host.utils.templates;

/**
 * Represents a descriptor for template files within the Java Runtime for Azure framework. This record encapsulates the necessary
 * information to identify and process template files, including their input and output filenames. Template descriptors
 * are used by the {@link TemplateEngine} to generate resources based on predefined templates, facilitating the dynamic
 * creation of application components and configurations.
 * <p>
 * The {@code inputFilename} specifies the location of the template file within the project's resources, while the
 * {@code outputFilename} determines the name of the file generated by the template engine. This approach allows for
 * flexible and maintainable template management, supporting a wide range of application scaffolding and configuration
 * tasks.
 *
 * @param inputFilename  The path to the input template file, relative to the project's resources directory.
 * @param outputFilename The name of the output file to be generated by the template engine, potentially including
 *                       dynamic parts based on template processing.
 */
public record TemplateDescriptor(String inputFilename, String outputFilename) {
}